# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "OegKorpJrczTRjZqqOTjLRIrYe1cNmZb2NmD2j9PTE41hko1uHZru3obnBTil9uqycFsBw80AgMxC/lRLulsx/T2TvTjmZtUJ+I42IpPijuqoAg6tcQJOTtCZRs6f3yfG27u6PQoqAVv+rYgvbVnKYatR7U6YaN6AT9RJufksL8luqFcQGgtLAuYtXG7BeYdVnwe2eXi+zBgZ8j9ys/qbwusTsNcHe37pcPj2hwlpBlWnEU6zprhitgzlP2jyPnyXZvFYoFKtEcAsf7PE4RLATvW8YXBgmpl9Vgr7+zKTHdhWSuxMDazkhyuQRxWVg4E2AYdUsGYLUO9K3Anz3CvtwLhaDisKrWYF/+OqQFavGupK0ZZ3PQtIM1eDuo/eBDtYW52dmCqH50uoyuqMmhTz15u2xLd+M3JT0l2AmB++plqXPVpkJZbNe0+mgIRfcWUJ2P8SMXzR/oIBf4jHUtDNuH/JgHKSSfMJDs7PXvVK2O8kcsQoDZ7OE9j0zVz7I5sPlCZXNNnBFoeRr4u7xdhMZyGiZ6WYmK1nRSweK3C2XfHiLVkLgMQm7CvQybuN6oP+gv7ELOCv5kdXifOJYOfgVGPqJYtSxB+5nqZAglZPcM0itrK4VbBu+AxbRNXhK9Kr+F7YVf1X1qbCWblm2fZWlA3bD1XNTIjJfERxnjMZ3Y="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
